language: node_js
node_js:
  - 14
  - 12
  - 10
env: 
    - CODECOV_TOKEN="45859a4f-e76a-4d71-8408-09774844c609"
script: 
      - yarn run test:cov

after_success:
  - bash <(curl -s https://codecov.io/bash)   
    